export { createOptq, getGetter, getSetter, getFetcher, getMutator } from "./lib.js";
export type {
  Util as OptqTypeUtil,
  Http,
  Optq,
  OptqApi,
  OptqConfig,
  OptqGetRouteConfig,
  OptqMutationRouteConfig,
  OptqRequestHeaders,
  OptqResponseHeaders,
  OptqRequest,
  OptqResponse,
  OptqRequestStore,
  OptqCacheStore,
  OptqPredictionStore,
  OptqSetter,
  OptqGetter,
  OptqFetcher,
  OptqMutator,
  GetRoutes,
  MutationRoutes,
} from "./types.js";
